name: Build and Release [Daily]

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Install packages
        run: yarn

      - name: Fetch Fontsource fontlist
        run: yarn fontlist

      - name: Parse
        run: yarn parse

      - name: Format
        run: yarn format

      - name: Stage changes
        run: git add --all

      - name: Commit files
        run: >-
          git commit -m "chore(build): update download counts [Daily $GITHUB_RUN_NUMBER]"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
