name: Build and Release [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == 'DecliningLotus'

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Install packages
        run: yarn

      - name: Fetch Fontsource fontlist
        run: yarn fontlist

      - name: Parse
        run: yarn parse

      - name: Format
        run: yarn format
        
      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "fontsource-bot"
          commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
          commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>" 
          commit_message: "chore(build): update download counts [Manual $GITHUB_RUN_NUMBER]"
        continue-on-error: true
