name: Build and Release [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Enable PNPM
        uses: pnpm/action-setup@v2

      - name: Set node version to 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install packages
        run: pnpm install

      - name: Parse
        run: yarn parse

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "fontsource-bot"
          commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
          commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>"
          commit_message: "chore(build): update download counts [Manual]"
        continue-on-error: true
